"""
Query Generator agent for Story 2.3.

Generates targeted RAG queries using hypothesis context, critic feedback,
and TaskSpec metadata. Executes PaperRAG searches and returns structured
results for hypothesis generation.
"""

from __future__ import annotations

import json
import os
import re
from copy import deepcopy
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence

import textwrap
import yaml

from camel.agents import ChatAgent
from camel.configs import ChatGPTConfig
from camel.messages import BaseMessage
from camel.models import ModelFactory
from camel.types import ModelPlatformType
from pydantic import BaseModel, Field

from aust.src.utils.logging_config import get_logger
from aust.src.utils.model_config import load_model_settings
from aust.src.data_models import CriticFeedback, Hypothesis
from aust.src.rag.vector_db import PaperRAG, SearchResult

logger = get_logger(__name__)

AUST_ROOT = Path(__file__).resolve().parents[2]
PROMPTS_DIR = AUST_ROOT / "configs" / "prompts"
QUERY_PROMPT_PATH = PROMPTS_DIR / "query_generator.yaml"

COLLECTION_TASK_TYPE_MAP = {
    "aust_papers_any_to_v": "any-to-v",
    "aust_papers_any_to_t": "any-to-t",
    "aust_papers": None,
}

IMAGE_MODEL_HINTS = {
    "stable diffusion",
    "sdxl",
    "diffusion",
    "text-to-image",
    "t2i",
    "image generation",
    "dreambooth",
    "imagen",
    "dall-e",
    "dalle",
    "deepfloyd",
}

TEXT_MODEL_HINTS = {
    "gpt",
    "llama",
    "llm",
    "text generation",
    "language model",
    "chat model",
    "bert",
    "mistral",
    "vicuna",
}

SECTION_ALIAS_MAP = {
    "quick_summary": "SUMMARY",
    "summary": "SUMMARY",
    "methodology": "METHODOLOGY",
    "core_method": "CORE_METHOD",
    "algorithm": "ALGORITHM_APPROACH",
    "algorithm/approach": "ALGORITHM_APPROACH",
    "implementation": "IMPLEMENTATION",
    "implementation_details": "IMPLEMENTATION",
    "potential_attack_methods": "ATTACK_METHODS",
    "attack_methods": "ATTACK_METHODS",
    "results": "RESULTS",
    "experiments": "EXPERIMENTS",
    "relevance": "RELEVANCE",
}

KNOWN_SECTIONS = {
    "METADATA",
    "SUMMARY",
    "METHODOLOGY",
    "CORE_METHOD",
    "ALGORITHM_APPROACH",
    "EXPERIMENTS",
    "RESULTS",
    "RELEVANCE",
    "IMPLEMENTATION",
    "ATTACK_METHODS",
    "FULL_PAPER",  # Added to support full paper chunks
}


_QUERY_MODEL_SETTINGS_FALLBACK = {
    "model_name": "openai/gpt-5-mini",
    "config": {
        "temperature": 0.2,
        "max_tokens": 1200,
    },
}

_QUERY_MODEL_SETTINGS = load_model_settings(
    "query_generator", _QUERY_MODEL_SETTINGS_FALLBACK
)
_DEFAULT_QUERY_MODEL = _QUERY_MODEL_SETTINGS["model_name"]
_DEFAULT_QUERY_MODEL_CONFIG = _QUERY_MODEL_SETTINGS.get("config", {})



@dataclass
class QueryCandidate:
    """Single query candidate generated by the agent."""

    query: str
    target_collection: Optional[str] = None
    focus_sections: list[str] = field(default_factory=list)


@dataclass
class QuerySearchResult:
    """Query paired with its PaperRAG search results."""

    query: str
    target_collection: Optional[str]
    results: list[SearchResult] = field(default_factory=list)
    focus_sections: list[str] = field(default_factory=list)


@dataclass
class QueryGenerationResult:
    """Aggregate result from the query generator."""

    search_results: list[QuerySearchResult]
    retrieved_papers: list[dict[str, Any]]

    def to_log_dict(self) -> dict[str, Any]:
        """Convert to JSON-serializable dictionary for logging."""
        return {
            "search_results": [
                {
                    "query": entry.query,
                    "target_collection": entry.target_collection,
                    "focus_sections": entry.focus_sections,
                    "results": [
                        {
                            "arxiv_id": res.arxiv_id,
                            "section": res.section,
                            "text": res.text,
                            "similarity_score": res.similarity_score,
                            "task_type": res.task_type,
                            "attack_level": res.attack_level,
                            "model_type": res.model_type,
                            "paper_title": res.paper_title,
                            "card_path": res.card_path,
                        }
                        for res in entry.results
                    ],
                }
                for entry in self.search_results
            ],
            "retrieved_papers": self.retrieved_papers,
        }


class QueryItemModel(BaseModel):
    """Structured output schema for a single query item."""

    query: str = Field(..., description="Query string for the RAG search")
    target_collection: Optional[str] = Field(
        default=None,
        description="Preferred Qdrant collection (e.g., aust_papers_any_to_v)",
    )
    focus_sections: list[str] = Field(
        default_factory=list,
        description="List of paper card sections to prioritize",
    )


class QueryResponseModel(BaseModel):
    """Structured output schema for the query generator."""

    queries: list[QueryItemModel] = Field(
        default_factory=list,
        description="List of proposed RAG queries",
    )


class QueryGeneratorAgent:
    """LLM-assisted query generator for PaperRAG searches."""

    DEFAULT_MODEL = _DEFAULT_QUERY_MODEL
    DEFAULT_MAX_QUERIES = 3
    DEFAULT_TOP_K = 5
    MAX_KEYWORD_TERMS = 2

    def __init__(
        self,
        rag: PaperRAG,
        model_name: Optional[str] = None,
        max_queries: int = DEFAULT_MAX_QUERIES,
        top_k: int = DEFAULT_TOP_K,
        output_dir: Optional[Path] = None,
    ):
        """
        Initialize Query Generator agent.

        Args:
            rag: PaperRAG instance for semantic search
            model_name: OpenRouter-compatible model name
            max_queries: Maximum number of queries to request
            top_k: Number of PaperRAG results per query
            output_dir: Directory for query logs
        """
        self.rag = rag
        self._model_config = deepcopy(_DEFAULT_QUERY_MODEL_CONFIG)
        self.model_name = model_name or self.DEFAULT_MODEL
        self.max_queries = max(1, max_queries)
        self.top_k = max(1, top_k)
        self.output_dir = output_dir or Path("aust/outputs/queries")
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self._prompt_config = self._load_prompt_config()
        system_prompt = self._prompt_config.get("system_prompt")
        if not isinstance(system_prompt, str) or not system_prompt.strip():
            raise ValueError(
                f"Query generator system prompt missing or invalid at {QUERY_PROMPT_PATH}"
            )
        self._user_prompt_template = self._prompt_config.get("user_prompt_template")
        if not isinstance(self._user_prompt_template, str) or not self._user_prompt_template.strip():
            raise ValueError(
                f"Query generator user prompt template missing or invalid at {QUERY_PROMPT_PATH}"
            )

        logger.info(
            "Initializing QueryGeneratorAgent with model=%s, max_queries=%s, top_k=%s",
            self.model_name,
            self.max_queries,
            self.top_k,
        )

        self._agent = self._create_agent(self.model_name, system_prompt=system_prompt.strip())
        self._context_section_chars = None
        self._response_model = QueryResponseModel

    def generate(
        self,
        *,
        iteration_number: int,
        task_spec: Optional[Mapping[str, Any]] = None,
        hypothesis: Optional[Hypothesis] = None,
        critic_feedback: Optional[CriticFeedback] = None,
        past_results: Optional[Sequence[dict[str, Any]]] = None,
    ) -> QueryGenerationResult:
        """
        Generate queries and execute PaperRAG search.

        Args:
            iteration_number: Current inner loop iteration
            task_spec: Structured TaskSpec dictionary (if available)
            hypothesis: Latest hypothesis to ground search
            critic_feedback: Feedback from critic agent
            past_results: Summaries of previous iterations

        Returns:
            QueryGenerationResult object containing queries and retrieved papers
        """
        prompt = self._build_prompt(
            iteration_number=iteration_number,
            task_spec=task_spec,
            hypothesis=hypothesis,
            critic_feedback=critic_feedback,
            past_results=past_results,
        )

        user_message = BaseMessage.make_user_message(
            role_name="Orchestrator", content=prompt
        )

        queries: list[QueryCandidate] = []
        try:
            logger.debug(
                "Invoking QueryGeneratorAgent LLM for iteration %s",
                iteration_number,
            )
            response = self._agent.step(
                user_message, response_format=self._response_model
            )
            raw_queries = self._extract_queries_from_response(response)
            if not raw_queries:
                raise RuntimeError("Query generator returned no queries.")
            queries = self._enforce_keyword_query_style(raw_queries)
            if not queries:
                raise RuntimeError("Query normalization produced no usable queries.")
        except Exception as exc:
            logger.error("Query generation failed: %s", exc, exc_info=True)
            raise
        finally:
            self._agent.reset()

        search_results = self._search_queries(queries, task_spec=task_spec)
        retrieved_papers = self._flatten_results(search_results)

        result = QueryGenerationResult(
            search_results=search_results,
            retrieved_papers=retrieved_papers,
        )

        self._log_queries(iteration_number, result, task_spec, hypothesis, critic_feedback)
        return result

    def _load_prompt_config(self) -> dict[str, Any]:
        """Load YAML prompt configuration for the query agent."""
        if not QUERY_PROMPT_PATH.exists():
            raise FileNotFoundError(f"Query prompt configuration not found at {QUERY_PROMPT_PATH}")

        with QUERY_PROMPT_PATH.open("r", encoding="utf-8") as handle:
            payload = yaml.safe_load(handle) or {}

        if not isinstance(payload, dict):
            raise ValueError(f"Query prompt configuration {QUERY_PROMPT_PATH} must be a YAML mapping")

        return payload

    def _render_task_spec_section(self, spec_dict: Optional[Mapping[str, Any]]) -> str:
        if not spec_dict:
            return "- No TaskSpec provided."

        lines: list[str] = []
        fields = [
            ("task_type", "Task Type"),
            ("model_name", "Model Name"),
            ("model_version", "Model Version"),
            ("base_model_path", "Base Model Path"),
            ("unlearned_model_path", "Unlearned Model Path"),
            ("unlearned_target", "Unlearned Target"),
            ("unlearning_method", "Unlearning Method"),
        ]
        for key, label in fields:
            value = spec_dict.get(key)
            if value:
                lines.append(f"- {label}: {value}")

        user_prompt = (spec_dict.get("user_prompt") or "").strip()
        if user_prompt:
            indented_prompt = textwrap.indent(user_prompt, "  ")
            lines.append("- User Prompt:\n" + indented_prompt)

        metadata = spec_dict.get("metadata")
        if isinstance(metadata, dict) and metadata.get("field_sources"):
            sources = metadata["field_sources"]
            if isinstance(sources, dict):
                origin_info = ", ".join(f"{k}: {v}" for k, v in sources.items())
                if origin_info:
                    lines.append(f"- Field sources: {origin_info}")

        return "\n".join(lines) if lines else "- TaskSpec metadata present but fields were empty."

    def _render_hypothesis_section(self, hypothesis: Optional[Hypothesis]) -> str:
        if not hypothesis:
            return "- No hypothesis generated yet. Base queries on TaskSpec context."

        description = (hypothesis.description or "").strip()
        if description:
            return f"- Description: {description}"
        return "- Hypothesis description unavailable."

    def _render_evaluation_section(self, past_results: Optional[Sequence[dict[str, Any]]]) -> str:
        if not past_results:
            return "- No evaluation results recorded yet."

        lines = []
        for summary in past_results:
            iteration = summary.get("iteration") or summary.get("iteration_number") or "?"
            outcome = summary.get("outcome") or "Outcome not recorded."
            confidence = summary.get("vulnerability_confidence")
            confidence_text = (
                f" (vulnerability confidence={float(confidence):.2f})"
                if isinstance(confidence, (int, float))
                else ""
            )

            lines.append(f"- Iteration {iteration}: {outcome}{confidence_text}")

        return "\n".join(lines)

    def _render_critic_section(self, critic_feedback: Optional[CriticFeedback]) -> str:
        if not critic_feedback:
            return "- No critic feedback available yet."

        lines = []
        assessment = (critic_feedback.overall_assessment or "").strip()
        if assessment:
            lines.append(f"- Assessment: {assessment}")

        if critic_feedback.suggestions:
            suggestion = critic_feedback.suggestions[0].strip()
            if suggestion:
                lines.append(f"- Primary suggestion: {suggestion}")

        # Commented out to reduce token usage for query generator (saves ~100 tokens)
        # lines.append(
        #     f"- Scores -> Novelty: {critic_feedback.novelty_score:.2f}, "
        #     f"Feasibility: {critic_feedback.feasibility_score:.2f}, "
        #     f"Rigor: {critic_feedback.rigor_score:.2f}"
        # )
        #
        # overall_assumption = (critic_feedback.overall_assumption or "").strip()
        # if overall_assumption:
        #     lines.append(f"- Critic assumption: {overall_assumption}")

        return "\n".join(lines)

    def _normalize_focus_sections(
        self, sections: Optional[Sequence[str]]
    ) -> list[Optional[str]]:
        if not sections:
            return []

        normalized: list[Optional[str]] = []
        seen: set[Optional[str]] = set()
        for raw in sections:
            if raw is None:
                continue
            candidate = str(raw).strip()
            if not candidate:
                continue
            key = candidate.lower().replace(" ", "_").replace("-", "_")
            mapped = SECTION_ALIAS_MAP.get(key)
            if mapped:
                section_value: Optional[str] = mapped
            else:
                upper = candidate.upper().replace(" ", "_").replace("-", "_")
                section_value = upper if upper in KNOWN_SECTIONS else None

            if section_value not in seen:
                seen.add(section_value)
                normalized.append(section_value)

        return normalized

    @staticmethod
    def _coerce_focus_sections(value: Any) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            return [value]
        if isinstance(value, Sequence):
            return [str(item) for item in value if str(item).strip()]
        return []

    def _enforce_keyword_query_style(
        self, candidates: Sequence[QueryCandidate]
    ) -> list[QueryCandidate]:
        """
        Ensure each RAG query is a single keyword or two-word phrase at most.
        """
        normalized: list[QueryCandidate] = []
        seen: set[str] = set()

        for candidate in candidates:
            fragments = self._split_into_keyword_fragments(candidate.query)
            if not fragments:
                continue
            for fragment in fragments:
                key = fragment.lower()
                if key in seen:
                    continue
                seen.add(key)
                normalized.append(
                    QueryCandidate(
                        query=fragment,
                        target_collection=candidate.target_collection,
                        focus_sections=list(candidate.focus_sections),
                    )
                )
                if len(normalized) >= self.max_queries:
                    return normalized

        if not normalized:
            fallback = [
                QueryCandidate(
                    query=candidate.query.strip(),
                    target_collection=candidate.target_collection,
                    focus_sections=list(candidate.focus_sections),
                )
                for candidate in candidates
                if candidate.query.strip()
            ]
            return fallback[: self.max_queries]

        return normalized

    def _split_into_keyword_fragments(self, raw_query: str) -> list[str]:
        if not isinstance(raw_query, str):
            return []

        cleaned = self._strip_parenthetical_blocks(raw_query)
        cleaned = (
            cleaned.replace("“", '"')
            .replace("”", '"')
            .replace("’", "'")
            .replace("–", " ")
            .replace("—", " ")
            .replace("−", " ")
        )

        fragments: list[str] = []
        quote_pattern = re.compile(r"(['\"])(.*?)\1")
        for match in quote_pattern.finditer(cleaned):
            phrase = match.group(2)
            fragments.extend(self._normalize_keyword_phrase(phrase))

        cleaned = quote_pattern.sub(" ", cleaned)
        cleaned = re.sub(r"\b(?:OR|AND|NOT)\b", " ", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"[,\|;:+]", " ", cleaned)
        cleaned = cleaned.replace("/", " ").replace("\\", " ")
        cleaned = re.sub(r"\s+", " ", cleaned).strip()

        if not cleaned:
            return fragments

        for chunk in cleaned.split(" "):
            fragments.extend(self._normalize_keyword_phrase(chunk))

        deduped: list[str] = []
        seen: set[str] = set()
        for fragment in fragments:
            key = fragment.lower()
            if key in seen:
                continue
            seen.add(key)
            deduped.append(fragment)

        return deduped

    @staticmethod
    def _strip_parenthetical_blocks(text: str) -> str:
        if not isinstance(text, str):
            return ""
        previous = None
        current = text
        # Remove nested parentheses iteratively.
        while previous != current:
            previous = current
            current = re.sub(r"\([^()]*\)", " ", current)
        return current

    def _normalize_keyword_phrase(self, phrase: Optional[str]) -> list[str]:
        if not phrase:
            return []
        safe = re.sub(r"[^\w\s\-./+]", " ", phrase)
        safe = re.sub(r"\s+", " ", safe).strip()
        if not safe:
            return []
        if not any(char.isalnum() for char in safe):
            return []

        words = safe.split()
        if len(words) <= self.MAX_KEYWORD_TERMS:
            return [safe]

        return [
            " ".join(words[idx : idx + self.MAX_KEYWORD_TERMS])
            for idx in range(len(words) - (self.MAX_KEYWORD_TERMS - 1))
        ]

    def _default_collection_for_task(
        self, spec_dict: Optional[Mapping[str, Any]]
    ) -> str:
        if not spec_dict:
            return "aust_papers"

        task_type = (spec_dict.get("task_type") or "").lower()
        model_name = (spec_dict.get("model_name") or "").lower()
        user_prompt = (spec_dict.get("user_prompt") or "").lower()
        hint_blob = " ".join([task_type, model_name, user_prompt])

        if any(hint in hint_blob for hint in IMAGE_MODEL_HINTS):
            return "aust_papers_any_to_v"

        if any(hint in hint_blob for hint in TEXT_MODEL_HINTS) or "any_to_t" in hint_blob:
            return "aust_papers_any_to_t"

        return "aust_papers"

    def _normalize_collection_name(self, collection: Optional[str], fallback: str) -> str:
        if isinstance(collection, str) and collection.strip():
            candidate = collection.strip()
            if candidate in COLLECTION_TASK_TYPE_MAP:
                return candidate
            lowered = candidate.lower()
            for key in COLLECTION_TASK_TYPE_MAP:
                if lowered == key.lower():
                    return key
        return fallback

    @staticmethod
    def _collection_to_task_type(collection_name: Optional[str]) -> Optional[str]:
        if not collection_name:
            return None
        return COLLECTION_TASK_TYPE_MAP.get(collection_name)

    def _infer_model_type_filter(self, spec_dict: Optional[Mapping[str, Any]]) -> Optional[str]:
        # Disable model_type filtering - papers use mixed types (T->I, T->V, etc.)
        # and we want to retrieve all relevant text-to-vision papers regardless of modality
        return None

        # Original logic below (commented out):
        # if not spec_dict:
        #     return None
        # task_type = (spec_dict.get("task_type") or "").lower()
        # model_name = (spec_dict.get("model_name") or "").lower()
        # hint_blob = " ".join([model_name, task_type, (spec_dict.get("user_prompt") or "").lower()])
        # if "concept_erasure" in task_type or any(hint in hint_blob for hint in IMAGE_MODEL_HINTS):
        #     return "T->V"  # This was filtering out T->I papers!
        # return None

    @staticmethod
    def _deduplicate_results(results: Sequence[SearchResult]) -> list[SearchResult]:
        deduped: dict[tuple[str, str], SearchResult] = {}
        for entry in results:
            key = (entry.arxiv_id, entry.section)
            if key not in deduped or entry.similarity_score > deduped[key].similarity_score:
                deduped[key] = entry

        return sorted(
            deduped.values(),
            key=lambda item: item.similarity_score,
            reverse=True,
        )

    def _create_agent(self, model_name: str, *, system_prompt: str) -> ChatAgent:
        """Create ChatAgent for query generation."""
        config_dict = deepcopy(self._model_config)
        config_dict.setdefault("n", 1)
        config = ChatGPTConfig(**config_dict)

        backend = ModelFactory.create(
            model_platform=ModelPlatformType.OPENAI_COMPATIBLE_MODEL,
            model_type=model_name,
            url="https://openrouter.ai/api/v1",
            api_key=os.getenv("OPENROUTER_API_KEY"),
            model_config_dict=config.as_dict(),
        )

        system_message = BaseMessage.make_assistant_message(
            role_name="QueryGenerator",
            content=system_prompt,
        )

        return ChatAgent(system_message=system_message, model=backend)

    def _extract_queries_from_response(
        self, response
    ) -> list[QueryCandidate]:
        """Extract query candidates from structured output or raw content."""
        if not response or not getattr(response, "msgs", None):
            return []

        last_message = response.msgs[-1]
        parsed_output = getattr(last_message, "parsed", None)
        if parsed_output is not None:
            return self._convert_structured_output(parsed_output)

        content = last_message.content if last_message else ""
        return self._parse_query_response(content)

    def _build_prompt(
        self,
        *,
        iteration_number: int,
        task_spec: Optional[Mapping[str, Any]],
        hypothesis: Optional[Hypothesis],
        critic_feedback: Optional[CriticFeedback],
        past_results: Optional[Sequence[dict[str, Any]]],
    ) -> str:
        """Construct user prompt for the LLM."""
        spec_dict = self._normalize_task_spec(task_spec)
        prompt = self._user_prompt_template.format(
            task_spec_section=self._render_task_spec_section(spec_dict),
            hypothesis_section=self._render_hypothesis_section(hypothesis),
            evaluation_section=self._render_evaluation_section(past_results),
            critic_section=self._render_critic_section(critic_feedback),
            max_queries=self.max_queries,
            iteration_number=iteration_number,
        )
        return prompt

    def _parse_query_response(self, response_text: str) -> list[QueryCandidate]:
        """Parse LLM response into query candidates."""
        json_match = re.search(r"```json\s*(\{.*?\})\s*```", response_text, re.DOTALL)
        json_str: Optional[str] = None
        if json_match:
            json_str = json_match.group(1)
        else:
            inline_match = re.search(r"(\{.*\})", response_text, re.DOTALL)
            if inline_match:
                json_str = inline_match.group(1)

        if not json_str:
            raise ValueError("JSON block not found in query generator response.")

        payload = json.loads(json_str)
        query_items = payload.get("queries", [])

        candidates: list[QueryCandidate] = []
        for item in query_items[: self.max_queries]:
            query_text = (item or {}).get("query")
            if not query_text:
                continue
            target_collection = (item or {}).get("target_collection")
            focus_sections = self._coerce_focus_sections((item or {}).get("focus_sections"))
            candidates.append(
                QueryCandidate(
                    query=query_text.strip(),
                    target_collection=str(target_collection).strip() if target_collection else None,
                    focus_sections=focus_sections,
                )
            )

        return candidates

    def _search_queries(
        self,
        queries: Sequence[QueryCandidate],
        task_spec: Optional[Mapping[str, Any]] = None,
    ) -> list[QuerySearchResult]:
        """Execute PaperRAG search for each query."""
        results: list[QuerySearchResult] = []
        spec_dict = self._normalize_task_spec(task_spec)
        default_collection = self._default_collection_for_task(spec_dict)
        model_type_filter = self._infer_model_type_filter(spec_dict)

        for candidate in queries:
            normalized_collection = self._normalize_collection_name(
                candidate.target_collection, default_collection
            )
            focus_sections = self._normalize_focus_sections(candidate.focus_sections)
            # Disable section filtering - search full papers only
            # section_filters = focus_sections or [None]

            task_type_filter = self._collection_to_task_type(normalized_collection)

            aggregated: list[SearchResult] = []
            try:
                # Search without section filter (always search FULL_PAPER)
                rag_results = self.rag.search(
                    query=candidate.query,
                    top_k=self.top_k,
                    section_filter=None,  # Disabled - papers are indexed as FULL_PAPER
                    task_type_filter=task_type_filter,
                    model_type_filter=model_type_filter,
                    similarity_threshold=0.15,  # Lowered to 0.15 for short keyword queries (was 0.5 → 0.3 → 0.15)
                )
                aggregated.extend(rag_results)
            except Exception as exc:
                logger.error("PaperRAG search failed for query '%s': %s", candidate.query, exc)
                aggregated = []

            deduped_results = self._deduplicate_results(aggregated)

            results.append(
                QuerySearchResult(
                    query=candidate.query,
                    target_collection=normalized_collection,
                    focus_sections=[section for section in focus_sections if section],
                    results=deduped_results[: self.top_k],
                )
            )

        return results

    def _flatten_results(
        self, search_results: Sequence[QuerySearchResult]
    ) -> list[dict[str, Any]]:
        """Flatten search results into list of dictionaries for HypothesisContext."""
        flattened: list[dict[str, Any]] = []
        seen_keys: set[tuple[str, str]] = set()

        for entry in search_results:
            for result in entry.results:
                key = (result.arxiv_id, result.section)
                if key in seen_keys:
                    continue
                seen_keys.add(key)
                flattened.append(
                    {
                        "title": result.paper_title,
                        "arxiv_id": result.arxiv_id,
                        "section": result.section,
                        "relevance_score": result.similarity_score,
                        "summary": result.text,
                        "task_type": result.task_type,
                        "attack_level": result.attack_level,
                        "model_type": result.model_type,
                        "source_query": entry.query,
                        "target_collection": entry.target_collection,
                        "focus_sections": entry.focus_sections,
                    }
                )

        return flattened

    def _log_queries(
        self,
        iteration_number: int,
        result: QueryGenerationResult,
        task_spec: Optional[Mapping[str, Any]],
        hypothesis: Optional[Hypothesis],
        critic_feedback: Optional[CriticFeedback],
    ):
        """Persist query generation details to JSON log."""
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        log_payload: dict[str, Any] = {
            "iteration": iteration_number,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "task_spec": self._normalize_task_spec(task_spec),
            "hypothesis": hypothesis.model_dump() if hypothesis else None,
            "critic_feedback": critic_feedback.model_dump() if critic_feedback else None,
            "result": result.to_log_dict(),
        }

        log_path = self.output_dir / f"queries_iter{iteration_number}_{timestamp}.json"
        try:
            with open(log_path, "w", encoding="utf-8") as handle:
                json.dump(
                    log_payload,
                    handle,
                    indent=2,
                    default=self._json_default,
                )
            logger.info("Logged query generation to %s", log_path)
        except Exception as exc:
            logger.error("Failed to write query log: %s", exc, exc_info=True)

    def _normalize_task_spec(
        self, task_spec: Optional[Mapping[str, Any]]
    ) -> Optional[dict[str, Any]]:
        """Convert TaskSpec object to a plain dictionary if possible."""
        if not task_spec:
            return None

        if isinstance(task_spec, Mapping):
            return {str(key): value for key, value in task_spec.items()}

        if hasattr(task_spec, "model_dump"):
            try:
                return task_spec.model_dump()
            except Exception:
                logger.debug("TaskSpec model_dump() failed", exc_info=True)

        if hasattr(task_spec, "dict"):
            try:
                return task_spec.dict()
            except Exception:
                logger.debug("TaskSpec dict() failed", exc_info=True)

        try:
            return dict(task_spec)
        except Exception:
            logger.warning("Unable to normalize TaskSpec; logging string representation.")
            return {"raw": str(task_spec)}

    def _json_default(self, obj):
        """Fallback serializer for datetimes and other unsupported types."""
        if isinstance(obj, datetime):
            return obj.isoformat()
        if hasattr(obj, "model_dump"):
            return obj.model_dump(mode="json")
        if isinstance(obj, Path):
            return str(obj)
        raise TypeError(f"Object of type {obj.__class__.__name__} is not JSON serializable")

    def _convert_structured_output(
        self, structured_output: Any
    ) -> list[QueryCandidate]:
        """Convert structured output (Pydantic model or dict) into candidates."""
        if structured_output is None:
            return []

        if isinstance(structured_output, BaseModel):
            data = structured_output.model_dump()
        elif isinstance(structured_output, dict):
            data = structured_output
        else:
            logger.warning(
                "Unexpected structured output type from query generator: %s",
                type(structured_output),
            )
            return []

        queries_data = data.get("queries", [])
        candidates: list[QueryCandidate] = []
        for item in queries_data[: self.max_queries]:
            if isinstance(item, BaseModel):
                item_dict = item.model_dump()
            elif isinstance(item, dict):
                item_dict = item
            else:
                logger.debug("Skipping non-dict query item: %s", item)
                continue
            query_text = (item_dict.get("query") or "").strip()
            if not query_text:
                continue
            target_collection = item_dict.get("target_collection")
            focus_sections = self._coerce_focus_sections(item_dict.get("focus_sections"))
            candidates.append(
                QueryCandidate(
                    query=query_text,
                    target_collection=str(target_collection).strip() if target_collection else None,
                    focus_sections=focus_sections,
                )
            )

        return candidates
