"""
Code synthesis data models for the code-repair-execute loop.

Defines the structured schemas for code artifacts, execution results, and
repair attempts used by the CodeSynthesizer agent.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator


class CodeArtifactStatus(str, Enum):
    """Status of a code artifact."""

    SYNTHESIZED = "synthesized"  # Generated but not yet executed
    EXECUTING = "executing"  # Currently being executed
    SUCCESS = "success"  # Executed successfully
    FAILED = "failed"  # Execution failed
    REPAIRED = "repaired"  # Repaired after failure


class CodeArtifact(BaseModel):
    """
    Represents a generated code artifact for concept-erasure attack.

    Generated by the CodeSynthesizer agent from a refined hypothesis.
    """

    artifact_id: str = Field(default_factory=lambda: str(uuid4()))
    code: str = Field(..., description="Generated Python code for the attack")
    language: str = Field(default="python", description="Programming language")
    status: CodeArtifactStatus = Field(
        default=CodeArtifactStatus.SYNTHESIZED,
        description="Current status of the artifact",
    )

    # Generation context
    hypothesis_id: str = Field(..., description="Source hypothesis ID")
    task_id: str = Field(..., description="Task ID")
    iteration_number: int = Field(..., ge=1, description="Iteration number")

    # Repair tracking
    parent_artifact_id: Optional[str] = Field(
        default=None, description="Parent artifact ID if this is a repair"
    )
    repair_attempt: int = Field(
        default=0, ge=0, description="Repair attempt number (0 for original)"
    )
    repair_feedback: Optional[str] = Field(
        default=None, description="Error feedback that prompted repair"
    )

    # Metadata
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Creation timestamp (timezone-aware)",
    )
    model_used: Optional[str] = Field(
        default=None, description="Model used for code generation"
    )
    tokens_used: Optional[int] = Field(default=None, description="Tokens used")

    @field_validator("created_at", mode="before")
    @classmethod
    def ensure_timezone_aware(cls, value: datetime) -> datetime:
        """Ensure datetime is timezone-aware (use UTC if naive)."""
        if value and value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value

    def mark_status(self, status: CodeArtifactStatus) -> None:
        """Update artifact status."""
        self.status = status

    def save_to_file(self, file_path: Path) -> Path:
        """
        Save code to file.

        Args:
            file_path: Path to save code file

        Returns:
            Path to saved file
        """
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(self.code, encoding="utf-8")
        return file_path


class ExecutionStatus(str, Enum):
    """Execution result status."""

    SUCCESS = "success"  # Code executed successfully
    FAILURE = "failure"  # Code execution failed
    TIMEOUT = "timeout"  # Execution timed out
    INTERRUPTED = "interrupted"  # Execution interrupted by user


class RunResult(BaseModel):
    """
    Results from executing a code artifact.

    Captures stdout, stderr, exit code, and execution metadata.
    """

    run_id: str = Field(default_factory=lambda: str(uuid4()))
    artifact_id: str = Field(..., description="Executed artifact ID")
    status: ExecutionStatus = Field(..., description="Execution status")

    # Execution outputs
    stdout: str = Field(default="", description="Standard output")
    stderr: str = Field(default="", description="Standard error output")
    exit_code: int = Field(default=0, description="Process exit code")

    # Error analysis
    error_summary: Optional[str] = Field(
        default=None, description="Brief error summary for repair agent"
    )
    error_snippet: Optional[str] = Field(
        default=None, description="Relevant error snippet extracted from stderr"
    )
    traceback: Optional[str] = Field(
        default=None, description="Full Python traceback if available"
    )

    # Execution metadata
    started_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Execution start time",
    )
    completed_at: Optional[datetime] = Field(
        default=None, description="Execution completion time"
    )
    timeout_seconds: Optional[int] = Field(
        default=None, description="Configured timeout in seconds"
    )

    # Output paths
    output_dir: Optional[Path] = Field(
        default=None, description="Directory containing execution outputs"
    )
    log_file: Optional[Path] = Field(
        default=None, description="Path to execution log file"
    )

    @property
    def duration_seconds(self) -> Optional[float]:
        """Calculate execution duration in seconds."""
        if self.completed_at and self.started_at:
            return (self.completed_at - self.started_at).total_seconds()
        return None

    @property
    def is_success(self) -> bool:
        """Check if execution was successful."""
        return self.status == ExecutionStatus.SUCCESS and self.exit_code == 0

    @property
    def is_repairable(self) -> bool:
        """
        Check if failure is potentially repairable.

        Timeouts and interrupts are generally not repairable through code changes.
        """
        return self.status == ExecutionStatus.FAILURE

    def extract_error_for_repair(self) -> str:
        """
        Extract concise error information for repair agent.

        Returns:
            Formatted error string for repair prompt
        """
        if self.is_success:
            return "No errors (execution succeeded)"

        parts = []

        if self.error_summary:
            parts.append(f"Error Summary: {self.error_summary}")

        if self.error_snippet:
            parts.append(f"Error Snippet:\n{self.error_snippet}")
        elif self.stderr:
            # Extract last N lines of stderr as snippet
            stderr_lines = self.stderr.strip().split("\n")
            snippet_lines = stderr_lines[-10:]  # Last 10 lines
            parts.append(f"Error Output (last 10 lines):\n" + "\n".join(snippet_lines))

        if self.exit_code != 0:
            parts.append(f"Exit Code: {self.exit_code}")

        if not parts:
            parts.append(f"Execution failed with status: {self.status.value}")

        return "\n\n".join(parts)

    def save_metadata(self, file_path: Path) -> Path:
        """
        Save run result metadata to JSON file.

        Args:
            file_path: Path to save metadata

        Returns:
            Path to saved file
        """
        import json

        file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(self.model_dump(mode="json"), f, indent=2, default=str)
        return file_path


class CodeRepairHistory(BaseModel):
    """
    Tracks the history of code-repair-execute attempts for a single hypothesis.

    Used to detect oscillations and limit retry budget.
    """

    hypothesis_id: str = Field(..., description="Source hypothesis ID")
    task_id: str = Field(..., description="Task ID")
    iteration_number: int = Field(..., ge=1, description="Iteration number")

    # Attempt tracking
    attempts: list[dict[str, Any]] = Field(
        default_factory=list,
        description="List of attempt records (artifact_id, run_result_id, status)",
    )
    max_attempts: int = Field(default=3, ge=1, le=5, description="Maximum retry budget")

    # State tracking
    current_attempt: int = Field(default=0, ge=0, description="Current attempt number")
    final_artifact: Optional[CodeArtifact] = Field(
        default=None, description="Final successful artifact (if any)"
    )
    final_run_result: Optional[RunResult] = Field(
        default=None, description="Final run result"
    )

    # Timestamps
    started_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Repair loop start time",
    )
    completed_at: Optional[datetime] = Field(
        default=None, description="Repair loop completion time"
    )

    @property
    def is_complete(self) -> bool:
        """Check if repair loop has completed (success or exhausted)."""
        return self.final_run_result is not None

    @property
    def is_success(self) -> bool:
        """Check if repair loop succeeded."""
        return self.final_run_result is not None and self.final_run_result.is_success

    @property
    def attempts_remaining(self) -> int:
        """Calculate remaining retry attempts."""
        return max(0, self.max_attempts - self.current_attempt)

    @property
    def should_continue(self) -> bool:
        """Check if loop should continue trying."""
        return not self.is_complete and self.attempts_remaining > 0

    def add_attempt(
        self, artifact: CodeArtifact, run_result: RunResult
    ) -> None:
        """
        Record an execution attempt.

        Args:
            artifact: Code artifact that was executed
            run_result: Execution result
        """
        self.current_attempt += 1
        self.attempts.append(
            {
                "attempt_number": self.current_attempt,
                "artifact_id": artifact.artifact_id,
                "run_result_id": run_result.run_id,
                "status": run_result.status.value,
                "is_success": run_result.is_success,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }
        )

        # Update final result if successful or exhausted
        if run_result.is_success or not self.should_continue:
            self.final_artifact = artifact
            self.final_run_result = run_result
            self.completed_at = datetime.now(timezone.utc)

    @property
    def duration_seconds(self) -> Optional[float]:
        """Calculate total repair loop duration."""
        if self.completed_at and self.started_at:
            return (self.completed_at - self.started_at).total_seconds()
        return None


def sanitize_prompt_for_filename(prompt: str, max_length: int = 50) -> str:
    """
    Convert prompt text to filesystem-safe slug for image filenames.

    Args:
        prompt: Raw prompt text to sanitize
        max_length: Maximum length of the sanitized slug (default 50)

    Returns:
        Sanitized filename slug (lowercase, underscores, alphanumeric only)

    Examples:
        >>> sanitize_prompt_for_filename("A photograph of a red apple")
        'a_photograph_of_a_red_apple'
        >>> sanitize_prompt_for_filename("Van Gogh style portrait!!!")
        'van_gogh_style_portrait'
        >>> sanitize_prompt_for_filename("Very " * 30)  # Long prompt
        'very_very_very_very_very_very_very_very_very_very'
        >>> sanitize_prompt_for_filename("###@@@")  # Only special chars
        'generated'
    """
    import re

    # Remove special characters, keep only alphanumeric and spaces/hyphens
    slug = re.sub(r"[^\w\s-]", "", prompt.lower())

    # Replace spaces and hyphens with underscores, collapse multiple underscores
    slug = re.sub(r"[-\s]+", "_", slug).strip("_")

    # Truncate to max_length, ensuring we don't cut in the middle of a word
    if len(slug) > max_length:
        slug = slug[:max_length].rstrip("_")

    # Fallback to "generated" if empty after sanitization
    return slug or "generated"


__all__ = [
    "CodeArtifact",
    "CodeArtifactStatus",
    "CodeRepairHistory",
    "ExecutionStatus",
    "RunResult",
    "sanitize_prompt_for_filename",
]
