"""
Hypothesis Generator data models.

Includes the structured schema for hypotheses produced by the generator agent
and the contextual payload passed into the workforce before each iteration.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator


class Hypothesis(BaseModel):
    """
    Represents a proposed vulnerability test for unlearning methods.

    Generated by the Hypothesis Generator agent and refined through
    debate with the Critic agent.
    """

    hypothesis_id: str = Field(default_factory=lambda: str(uuid4()))
    attack_type: str = Field(
        ...,
        description="Type of attack (e.g., 'membership_inference', 'model_inversion', 'concept_leakage')",
    )
    description: str = Field(
        ..., description="Natural language description of the hypothesis"
    )
    experiment_design: str = Field(
        ..., description="Step-by-step experiment plan with implementation details and parameters"
    )
    target_type: str = Field(
        ..., description="Abstract category of the unlearned target (e.g., object, style, abstract)"
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Generator's confidence in hypothesis success",
    )
    novelty_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Estimated novelty based on memory/RAG similarity, the less similar the better",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Hypothesis generation timestamp (timezone-aware)",
    )

    @field_validator("confidence_score", "novelty_score", mode="before")
    @classmethod
    def clamp_scores(cls, value: float) -> float:
        """Clamp scores into valid range prior to numeric validation."""
        if value is None:
            return value
        try:
            numeric_value = float(value)
        except (TypeError, ValueError):
            return value
        return max(0.0, min(1.0, numeric_value))

    @field_validator("generated_at", mode="before")
    @classmethod
    def ensure_timezone_aware(cls, value: datetime) -> datetime:
        """Ensure datetime is timezone-aware (use UTC if naive)."""
        if value and value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value


class HypothesisContext(BaseModel):
    """
    Context information for hypothesis generation.

    Provides the Hypothesis Generator with all necessary information
    to create informed, relevant hypotheses.
    """

    iteration_number: int = Field(..., ge=1, description="Current iteration number")
    past_results: Optional[list[dict]] = Field(
        default=None, description="Summaries of past iteration results"
    )
    evaluator_feedback: Optional[str] = Field(
        default=None,
        description="Feedback from previous iteration's evaluator (step 4)",
    )
    retrieved_papers: Optional[list[dict]] = Field(
        default=None, description="Paper chunks retrieved from RAG system"
    )
    memory_entries: Optional[list[dict]] = Field(
        default=None, description="Similar successful hypotheses from memory"
    )
    seed_template: Optional[dict] = Field(
        default=None, description="Seed attack template for first iteration"
    )
    task_spec: Optional[dict[str, Any]] = Field(
        default=None,
        description="Structured TaskSpec information for this task",
    )
    critic_feedback_summaries: Optional[list[dict[str, Any]]] = Field(
        default=None,
        description="Recent critic feedback summaries to guide new hypotheses (inner loop from critic)",
    )


__all__ = ["Hypothesis", "HypothesisContext"]

